/**
 * MACP Research Assistant — Markdown Report Generator
 *
 * Converts paper + analysis results into a human-readable Markdown document.
 * JSON is for agents. Markdown is for both humans AND agents.
 * The generated file can be pasted directly into Claude, ChatGPT, or Perplexity.
 */

import type { Paper, Analysis, DeepAnalysis, Consensus, SectionAnalysis } from "../api/types";

// -----------------------------------------------------------------------
// Helpers
// -----------------------------------------------------------------------

function bulletList(items: string[] | undefined): string {
  if (!items || items.length === 0) return "_None identified._";
  return items.map((i) => `- ${i}`).join("\n");
}

function tagLine(items: string[] | undefined): string {
  if (!items || items.length === 0) return "_None_";
  return items.map((i) => `\`${i}\``).join("  ");
}

function formatSectionPass(s: SectionAnalysis): string {
  const d = s.data;
  const lines: string[] = [`#### ${s.pass.charAt(0).toUpperCase() + s.pass.slice(1)} Pass`];

  if (typeof d.summary === "string") {
    lines.push(`\n${d.summary}`);
  }
  if (typeof d.novelty_assessment === "string") {
    lines.push(`\n**Novelty Assessment:** ${d.novelty_assessment}`);
  }
  if (typeof d.technical_approach === "string") {
    lines.push(`\n**Technical Approach:** ${d.technical_approach}`);
  }
  if (typeof d.methodology_detail === "string") {
    lines.push(`\n**Methodology:** ${d.methodology_detail}`);
  }
  if (typeof d.reproducibility === "string") {
    lines.push(`\n**Reproducibility:** ${d.reproducibility}`);
  }
  if (Array.isArray(d.key_contributions)) {
    lines.push(`\n**Key Contributions:**\n${(d.key_contributions as string[]).map((i) => `- ${i}`).join("\n")}`);
  }
  if (Array.isArray(d.key_findings)) {
    lines.push(`\n**Key Findings:**\n${(d.key_findings as string[]).map((i) => `- ${i}`).join("\n")}`);
  }
  if (Array.isArray(d.limitations)) {
    lines.push(`\n**Limitations:**\n${(d.limitations as string[]).map((i) => `- ${i}`).join("\n")}`);
  }
  if (Array.isArray(d.future_work)) {
    lines.push(`\n**Future Work:**\n${(d.future_work as string[]).map((i) => `- ${i}`).join("\n")}`);
  }
  if (Array.isArray(d.datasets_used) && (d.datasets_used as string[]).length > 0) {
    lines.push(`\n**Datasets:** ${(d.datasets_used as string[]).join(", ")}`);
  }
  if (typeof d.strength_score === "number") {
    lines.push(`\n**Strength Score:** ${d.strength_score}/10`);
  }

  return lines.join("\n");
}

// -----------------------------------------------------------------------
// Main generator
// -----------------------------------------------------------------------

export function generateMarkdown(
  paper: Paper,
  analysis?: Analysis,
  deepAnalysis?: { analysis: DeepAnalysis; pageCount: number; sectionsExtracted: number } | null,
  consensus?: Consensus | null,
): string {
  const today = new Date().toISOString().split("T")[0];
  const provider = analysis?._meta?.provider
    ?? deepAnalysis?.analysis._meta?.provider
    ?? "gemini";
  const model = analysis?._meta?.model
    ?? deepAnalysis?.analysis._meta?.model
    ?? provider;
  const arxivId = paper.id.replace("arxiv:", "");
  const jsonPath = `.macp/analyses/${paper.id.replace("arxiv:", "arxiv_")}/${provider}_${today.replace(/-/g, "")}.json`;

  const L: string[] = [];

  // ---- Header ----
  L.push(`# ${paper.title}`);
  L.push(``);
  L.push(`> **ArXiv:** [${paper.id}](https://arxiv.org/abs/${arxivId})  `);
  L.push(`> **Provider:** ${model}  `);
  L.push(`> **Generated:** ${today}  `);
  if (paper.authors.length > 0) {
    L.push(`> **Authors:** ${paper.authors.join(", ")}  `);
  }
  L.push(`>`);
  L.push(`> *Generated by [MACP Research Assistant](https://macpresearch.ysenseai.org) — Multi-Agent Collaboration Platform v2.0*`);
  L.push(``);
  L.push(`---`);
  L.push(``);

  // ---- Abstract ----
  if (paper.abstract) {
    L.push(`## Abstract`);
    L.push(``);
    L.push(paper.abstract);
    L.push(``);
    L.push(`---`);
    L.push(``);
  }

  // ---- AI Analysis (abstract-level) ----
  if (analysis) {
    L.push(`## AI Analysis`);
    L.push(``);
    L.push(`**Strength Score:** ${analysis.strength_score}/10 | **Model:** ${analysis._meta?.model ?? analysis._meta?.provider ?? provider}`);
    L.push(``);

    L.push(`### Summary`);
    L.push(``);
    L.push(analysis.summary);
    L.push(``);

    if (analysis.key_insights.length > 0) {
      L.push(`### Key Insights`);
      L.push(``);
      L.push(bulletList(analysis.key_insights));
      L.push(``);
    }

    if (analysis.methodology) {
      L.push(`### Methodology`);
      L.push(``);
      L.push(analysis.methodology);
      L.push(``);
    }

    if (analysis.research_gaps.length > 0) {
      L.push(`### Research Gaps`);
      L.push(``);
      L.push(bulletList(analysis.research_gaps));
      L.push(``);
    }

    if (analysis.relevance_tags.length > 0) {
      L.push(`### Relevance Tags`);
      L.push(``);
      L.push(tagLine(analysis.relevance_tags));
      L.push(``);
    }

    if (analysis._meta?.bias_disclaimer) {
      L.push(`> ⚠️ *${analysis._meta.bias_disclaimer}*`);
      L.push(``);
    }

    L.push(`---`);
    L.push(``);
  }

  // ---- Deep Analysis (full-text multi-pass) ----
  if (deepAnalysis) {
    const deep = deepAnalysis.analysis;
    const passes = deep._meta?.passes ?? deepAnalysis.sectionsExtracted;

    L.push(`## Deep Analysis (${passes}-Pass Full-Text PDF)`);
    L.push(``);
    L.push(`**Strength Score:** ${deep.strength_score}/10 | **Pages:** ${deepAnalysis.pageCount} | **Sections Extracted:** ${deepAnalysis.sectionsExtracted} | **Model:** ${deep._meta?.model ?? ""}`);
    L.push(``);

    L.push(`### Summary`);
    L.push(``);
    L.push(deep.summary);
    L.push(``);

    if (deep.key_contributions.length > 0) {
      L.push(`### Key Contributions`);
      L.push(``);
      L.push(bulletList(deep.key_contributions));
      L.push(``);
    }

    if (deep.methodology_detail) {
      L.push(`### Detailed Methodology`);
      L.push(``);
      L.push(deep.methodology_detail);
      L.push(``);
    }

    if (deep.limitations.length > 0) {
      L.push(`### Limitations`);
      L.push(``);
      L.push(bulletList(deep.limitations));
      L.push(``);
    }

    const hasFutureWork = deep.future_work.length > 0
      && !deep.future_work[0].startsWith("The provided text does not contain");
    if (hasFutureWork) {
      L.push(`### Future Work`);
      L.push(``);
      L.push(bulletList(deep.future_work));
      L.push(``);
    }

    if (deep.research_gaps.length > 0) {
      L.push(`### Research Gaps`);
      L.push(``);
      L.push(bulletList(deep.research_gaps));
      L.push(``);
    }

    if (deep.relevance_tags.length > 0) {
      L.push(`### Relevance Tags`);
      L.push(``);
      L.push(tagLine(deep.relevance_tags));
      L.push(``);
    }

    // Section-by-section passes
    if (deep.section_analyses.length > 0) {
      L.push(`### Section-by-Section Analysis`);
      L.push(``);
      for (const section of deep.section_analyses) {
        L.push(formatSectionPass(section));
        L.push(``);
      }
    }

    if (deep._meta?.extraction_warnings && deep._meta.extraction_warnings.length > 0) {
      L.push(`> ⚠️ **Extraction Warning:** Analysis may be incomplete — PDF text extraction was limited. HTML fallback was used.`);
      L.push(``);
    }

    if (deep._meta?.bias_disclaimer) {
      L.push(`> ⚠️ *${deep._meta.bias_disclaimer}*`);
      L.push(``);
    }

    L.push(`---`);
    L.push(``);
  }

  // ---- Multi-Agent Consensus ----
  if (consensus) {
    L.push(`## Multi-Agent Consensus`);
    L.push(``);
    L.push(`**Agreement Score:** ${consensus.agreement_score.toFixed(0)}% | **Agents:** ${consensus.agents_compared.join(", ")} | **Generated:** ${consensus.generated_at.split("T")[0]}`);
    L.push(``);

    L.push(`### Synthesized Summary`);
    L.push(``);
    L.push(consensus.synthesized_summary);
    L.push(``);

    if (consensus.convergence_points.length > 0) {
      L.push(`### Points of Convergence`);
      L.push(``);
      L.push(bulletList(consensus.convergence_points));
      L.push(``);
    }

    if (consensus.divergence_points.length > 0) {
      L.push(`### Points of Divergence`);
      L.push(``);
      for (const d of consensus.divergence_points) {
        L.push(`**${d.topic}**`);
        L.push(``);
        for (const [agent, position] of Object.entries(d.positions)) {
          L.push(`- *${agent}:* ${position}`);
        }
        if (d.resolution) L.push(`- *Resolution:* ${d.resolution}`);
        L.push(``);
      }
    }

    if (consensus.recommended_action) {
      L.push(`### Recommended Action`);
      L.push(``);
      L.push(consensus.recommended_action);
      L.push(``);
    }

    if (consensus.bias_cross_check) {
      L.push(`### Bias Cross-Check`);
      L.push(``);
      L.push(consensus.bias_cross_check);
      L.push(``);
    }

    L.push(`---`);
    L.push(``);
  }

  // ---- Usage notes ----
  L.push(`## How to Use This Report`);
  L.push(``);
  L.push(`Paste into any LLM for deeper analysis:`);
  L.push(``);
  L.push(`- **Claude / ChatGPT / Gemini** — Ask follow-up questions, request comparisons, generate literature review`);
  L.push(`- **Perplexity Deep Research (SONAR)** — Feed this as context for an expanded search-backed analysis`);
  L.push(`- **Share with collaborators** — Structured research brief, ready to discuss`);
  L.push(`- **Cite and track** — Return to [MACP Research Assistant](https://macpresearch.ysenseai.org) to run consensus across multiple agents`);
  L.push(``);
  L.push(`**Agent-readable JSON (for AI pipelines):**`);
  L.push(`\`\`\``);
  L.push(jsonPath);
  L.push(`\`\`\``);
  L.push(``);
  L.push(`---`);
  L.push(``);
  L.push(`*[MACP Research Assistant](https://macpresearch.ysenseai.org) — Multi-Agent Collaboration Platform v2.0 | Source: [creator35lwb-web/macp-research-assistant](https://github.com/creator35lwb-web/macp-research-assistant)*`);

  return L.join("\n");
}

// -----------------------------------------------------------------------
// Browser download trigger
// -----------------------------------------------------------------------

export function downloadMarkdown(filename: string, content: string): void {
  const blob = new Blob([content], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
